#!/usr/bin/env bash
# Install Ngnix webserver
sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's|/var/www/html|/var/www/current/html|g' /etc/nginx/sites-available/default
sudo mkdir -p /var/www/current/html
sudo chown -R "$USER":"$USER" /var/www/current/html
sudo chmod -R 755 /var/www
echo "<html>
        <head>
        </head>
        <body>
           Hello World!
        </body>
      </html>" | sudo tee /var/www/current/html/index.html
sudo service nginx restart
