#!/usr/bin/env bash
# Install nginx on server which listens on port 80
apt-get -y update
apt-get -y install nginx
echo "<html><body>Hello World</body></html>" > /var/www/html/index.html
service nginx restart
