#!/usr/bin/env bash
# Redirect to another page
sudo apt-get update
sudo apt-get install -y nginx
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
# sudo sed -i '/listen 80 default_server;/a\\tdefault_type text/plain;' /etc/nginx/sites-available/default
# sudo sed -i '/location \/a\/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t' /etc/nginx/sites-available/default
sudo sed -i '/listen 80 default_server;/a location /redirect_me {\n\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-available/default
sudo service nginx restart
