#!/usr/bin/env bash
# Configur nginx to have a custom 404 page
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
echo 'Ceci n'\''est pas une page' > /var/www/html/404.html
cat <<EOF > /etc/nginx/sites-enabled/default
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
	error_page 404 /404.html
        location /404 {
                internal;
        }
}
EOF
service nginx restart
