#!/usr/bin/env bash
# Custom 404 page
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i '/listen 80 default_server;/a error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
sudo service nginx restart
