#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
apt-get -y update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*

cat <<EOF > /etc/haproxy/haproxy.cfg
frontend http-in
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    server 281593-web-01 18.207.2.71
    server 281593-web-02 54.157.142.152
EOF
haproxy -c -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
