#!/usr/bin/env bash
# Ngnix must listen on port 80 of all the server's active IPV4 IPS
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-avaliable/default /etc/nginx/sites-enabled/default
service nginx reload
