#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID
# Displays a text indefinitely
# displays another text when receiving a SIGTERM signal and a SIGINT
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
echo $$ | sudo tee /var/run/myscript.pid
trap "echo 'I hate the kill command'; sudo rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
while :
do
	echo "To infinity and beyond"
	sleep 2
done
