#!/usr/bin/env bash
# Displays a text indefinitely
# displays another text when receiving a SIGTERM signal
trap "echo 'I am invincible!!!'" SIGTERM
while :
do
	echo "To infinity and beyond"
	sleep 2
done
