#!/usr/bin/env bash
# Display content of /etc/passwd using while loop and using 7 variables
# delimited by : using IFS(Internal field separator)
while IFS=":" read -r username password user_id group_id user_id_info home_dir shell
do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $user_id_info"
done < /etc/passwd
