#!/usr/bin/env bash
# This script displays "Best School" 10 times, on the 9th, it also
# displays "Hi"
n=1
while [ $n -le 10 ]
do
	echo "Best School"
	if [ $n -eq 9 ]
	then
		echo "Hi"
	fi
	n=$((n + 1))
done
